name: release
on:
    push:
        branches: [main]
# jobs:
#   build:
# runs-on: ubuntu-latest# steps:
#    -name: Checkout code
#    uses: actions/checkout@v2
#  - name: create Release
#        draft: false
#        prerelease: false
